sudo: false
language: cpp
cache:
  directories:
  - $HOME/sdk_cache
before_install:
  - git submodule update --init --recursive
install:
  - cd $TRAVIS_BUILD_DIR
  - if [ -e $HOME/sdk_cache/esp-open-sdk.tar.gz ]; then tar -xzf $HOME/sdk_cache/esp-open-sdk.tar.gz; fi
before_cache:
  - mkdir -p $HOME/sdk_cache
  - cd $TRAVIS_BUILD_DIR
  - rm build/esp-open-sdk/esp_iot_sdk*zip
  - tar -czf $HOME/sdk_cache/esp-open-sdk.tar.gz build/.toolchain.* build/esp-open-sdk/.cache_copied build/.submodules build/esp-open-sdk/xtensa-lx106-elf build/esp-open-sdk/*sdk*
addons:
  apt:
    packages:
    - libtool
    - gperf
    - flex
    - bison
    - texinfo
    - gawk
    - python-serial
    - srecord
script:
- unset CC
- unset CXX
- export BUILD_DATE=$(date +%Y%m%d)
- make EXTRA_CCFLAGS="-DBUILD_DATE='\"'$BUILD_DATE'\"'" all
- cd bin/
- file_name_float="nodemcu_float_${TRAVIS_TAG}.bin"
- srec_cat -output ${file_name_float} -binary 0x00000.bin -binary -fill 0xff 0x00000 0x10000 0x10000.bin -binary -offset 0x10000
- cd ../
- make clean
- make EXTRA_CCFLAGS="-DLUA_NUMBER_INTEGRAL -DBUILD_DATE='\"'$BUILD_DATE'\"'" all
- cd bin/
- file_name_integer="nodemcu_integer_${TRAVIS_TAG}.bin"
- srec_cat -output ${file_name_integer} -binary 0x00000.bin -binary -fill 0xff 0x00000 0x10000 0x10000.bin -binary -offset 0x10000
# http://docs.travis-ci.com/user/environment-variables/#Convenience-Variables
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash "$TRAVIS_BUILD_DIR"/tools/pr-build.sh; fi
deploy:
  provider: releases
  api_key:
    secure: Swecz5lWvsuSbchSbVQ1rmCPN9nQIN5p/HlZNIEdEgAgnoLcJxRV4P8poVTB37jiA8Pck+8x2nWXpg74Rqik0i3KlPNvDfg5o4rIazWLNs4bc1Tbcpt44XAzFKKLYnDnWQUGcqjk7BcAXuNAF2X/fPBCVhFbHVg3Z7cDb32RsNw=
  file:
    - "$TRAVIS_BUILD_DIR/bin/${file_name_float}"
    - "$TRAVIS_BUILD_DIR/bin/${file_name_integer}"
  skip_cleanup: true
  on:
    tags: true
    repo: nodemcu/nodemcu-firmware
